import type { Metadata } from "next";
import localFont from "next/font/local";
import { Space_Grotesk } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["300", "400", "500",  "600", "700"],
});

const advanced_pixel_lcd = localFont({
  src: [
    {
      path: "../../public/fonts/advanced_pixel/advanced_pixel_lcd-7.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-advanced-pixel-lcd",
});

// export const metadata: Metadata = {
//   title: "Serhii Kushnir WEB DEV",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Full Stack Dev Serhii Kushnir",
  description:
    "Hi, I'm a full-stack developer with an engineering background, specializing in scalable and efficient solutions for both team and individual projects.",
  openGraph: {
    title: "Full Stack Dev Serhii Kushnir",
    description:
      "Hi, I'm a full-stack developer with an engineering background, specializing in scalable and efficient solutions for both team and individual projects.",
    url: "https://fullstack-dev-sk.vercel.app/", // Your website URL
    type: "website",
    images: [
      {
        url: "images/full_stack_dev_serhii_kushnir.png", // Full URL required
        width: 1200,
        height: 630,
        alt: "Full Stack Dev Serhii Kushnir",
      },
    ],
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/icons/favicon.svg"></link>
      </head>
      <body className={`${advanced_pixel_lcd.className} ${advanced_pixel_lcd.variable} ${spaceGrotesk.className} ${spaceGrotesk.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
